"""Initial migration

Revision ID: 9c3f55bac211
Revises: 
Create Date: 2026-05-14 14:07:34.136892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c3f55bac211'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_family_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'families', ['family_id'], ['id'])
    op.alter_column('families', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('families_invite_code_key'), 'families', type_='unique')
    op.create_index(op.f('ix_families_invite_code'), 'families', ['invite_code'], unique=True)
    op.drop_constraint(op.f('product_subscriptions_user_id_fkey'), 'product_subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('product_subscriptions_product_id_fkey'), 'product_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'product_subscriptions', 'users', ['user_id'], ['telegram_id'])
    op.create_foreign_key(None, 'product_subscriptions', 'products', ['product_id'], ['id'])
    op.drop_column('product_subscriptions', 'created_at')
    op.alter_column('products', 'lemma',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('idx_products_family'), table_name='products')
    op.drop_constraint(op.f('products_family_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'products', 'families', ['family_id'], ['id'])
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'updated_at')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.drop_constraint(op.f('users_family_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'families', ['family_id'], ['id'])
    op.drop_column('users', 'joined_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_family_id_fkey'), 'users', 'families', ['family_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('products_family_id_fkey'), 'products', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_products_family'), 'products', ['family_id'], unique=False)
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'quantity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'lemma',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('product_subscriptions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'product_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('product_subscriptions_product_id_fkey'), 'product_subscriptions', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('product_subscriptions_user_id_fkey'), 'product_subscriptions', 'users', ['user_id'], ['telegram_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_families_invite_code'), table_name='families')
    op.create_unique_constraint(op.f('families_invite_code_key'), 'families', ['invite_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('families', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_family_id_fkey'), 'categories', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
